
## World properties
# moon.sdf / moon 
# mars.sdf / mars 
# inspection.sdf / default
# marsyard2022.sdf / marsyard2022
# marsyard2020_walls.sdf / marsyard2020_walls
world_file: marsyard2020_walls.sdf
world_name: marsyard2020_walls                # for topic bridge (dependant of the environment name) - noramly the same as world_file... but not always

## Robot fleet properties
robot_ns: fleet                 # for tf relay
robots:
- name: fleet_0
  type: scoutv2
  pose: [0, 0, 3.5, 0, 0, 0]
- name: fleet_1
  type: scoutv2
  pose: [2, 2, 3.5, 0, 0, 0]
- name: fleet_2
  type: nasa_ingenuity
  pose: [2, -2.5, 3.6, 3.14, 0, 0]  
